### ISSUE TITLE
关于蒸馏的一些问题

### ISSUE THREAD

**Issue by EveningLin** [Shengcao-Cao/MTPD#1]
你好，非常好的工作！你们代码现在好像还没有realse！很期待你们transform蒸馏CNN的操作！我最近也是刚开始搞蒸馏，我有两个问题：
（1）图一中使用的卷积老师和transform老师是什么？学生模型又是什么？能不能同时释出这一段代码呢
（2）其次是如果使用logit蒸馏而不是直接对特征表示的L2蒸馏更好？

**Comment by Shengcao-Cao** [comment]
您好 @EveningLin ，

1）图一中的学生模型是以ResNet-50作为backbone的RetinaNet或Mask R-CNN。我们的MTPD采用多个Transformer教师模型，在这里是以Swin-T（第一个教师）和Swin-S（第二个教师）作为backbone的RetinaNet或Mask R-CNN。这里的模型已经放出，训练过程也已经说明，详情请看首页的Model Weights和Usage这两节。

2）就我理解，目前使用特征进行蒸馏是目标检测模型蒸馏的主流方向，通常会比使用logit蒸馏效果更佳。您也可以自己尝试一下不同的蒸馏方法。

**Comment by EveningLin** [comment]
非常感谢！！！
